"""empty message

Revision ID: 1e99ee4846cd
Revises: d7991f7e15d1
Create Date: 2022-05-01 18:43:22.770670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e99ee4846cd'
down_revision = 'd7991f7e15d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Post_user_fkey', 'Post', type_='foreignkey')
    op.create_foreign_key(None, 'Post', 'User', ['user'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Post', type_='foreignkey')
    op.create_foreign_key('Post_user_fkey', 'Post', 'User', ['user'], ['id'])
    # ### end Alembic commands ###
