"""empty message

Revision ID: 47bedb23ea65
Revises: cb6286241853
Create Date: 2022-05-01 20:01:42.814558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47bedb23ea65'
down_revision = 'cb6286241853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('Post', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Post', 'username')
    # ### end Alembic commands ###
