"""empty message

Revision ID: 7bce9e9bf5e5
Revises: 35c38c58a079
Create Date: 2022-04-25 11:20:11.979966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bce9e9bf5e5'
down_revision = '35c38c58a079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('timestamp', sa.TIMESTAMP()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Post', 'timestamp')
    # ### end Alembic commands ###
