"""empty message

Revision ID: b33a0e673402
Revises: 2eac516235f6
Create Date: 2022-04-24 22:26:05.380424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33a0e673402'
down_revision = '2eac516235f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'firstname')
    op.drop_column('User', 'lastname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
