"""empty message

Revision ID: c09d35253597
Revises: 9e512bfa90ea
Create Date: 2022-05-01 19:21:26.968156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09d35253597'
down_revision = '9e512bfa90ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('Post_user_fkey', 'Post', type_='foreignkey')
    op.create_foreign_key(None, 'Post', 'User', ['user_id'], ['id'])
    op.drop_column('Post', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Post', type_='foreignkey')
    op.create_foreign_key('Post_user_fkey', 'Post', 'User', ['user'], ['id'])
    op.drop_column('Post', 'user_id')
    # ### end Alembic commands ###
