"""empty message

Revision ID: cb6286241853
Revises: c09d35253597
Create Date: 2022-05-01 19:38:52.522562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6286241853'
down_revision = 'c09d35253597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Post', sa.Column('user', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Post', 'user')
    # ### end Alembic commands ###
