"""empty message

Revision ID: dcec0ea3eac2
Revises: 7bce9e9bf5e5
Create Date: 2022-04-28 12:34:03.429014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcec0ea3eac2'
down_revision = '7bce9e9bf5e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
